title: Data.gouv.fr Docs
description: >
    La documentation du site data.gouv.fr

twitter_username: etalab
github_username:  etalab

sass:
    style: compressed


exclude:
  - README.md
  - docker-compose.yml
  - circle.yml
  - deploy
  - Gemfile
  - Gemfile.lock
  - vendor


collections:
  faq:
    title: Découvrir l'OpenData
    output: true
    order: 1


defaults:
  - scope:
      path: ""
    values:
      layout: page
