title: Data.gouv.fr Docs
#author: Panoramedia
#email: panoramedia@gmail.com
description: > 
    La documentation du site data.gouv.fr 

twitter_username: etalab
github_username:  etalab

sass:
    style: compressed
