version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-stretch

    working_directory: ~/doc.data.gouv.fr

    steps:
      - checkout

      - run:
          name: Ruby dependencies
          command: bundle install

      - run:
          name: Build
          command: bundle exec jekyll build --verbose

      - run:
          name: Test
          command: bundle exec htmlproofer ./_site --check-html --disable-external

      - run:
          name: Deploy
          command: ./deploy
